config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :photos do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :file
  has_many :comments

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true

  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @photo = Photo.find(params[:photo_id])
      @comment = current_user.comments.create(comments_params.merge(photo_id: @photo.id))
      if @comment.save
        redirect_to photo_path(@comment.photo), notice: 'Comment done!'
      else
        redirect_to root_path, alert: 'Something went wrong'
      end
    end

    private
      def comments_params
        params.require(:comment).permit(:photo_id, :body)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    if current_user
      @photo = Photo.new
    else
      redirect_to root_path, alert: 'You must be logged in'
    end
  end

  def create
    @photo = current_user.photos.create(params_photo)
      if @photo.save
      redirect_to @photo
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
      redirect_to user_path(@photo.user)
    end
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :photo_path
    end
  end

private
  def params_photo
    params.require(:photo).permit(:caption, :file)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now[:alert] = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'Signed up!'
    end
      redirect_to new
  end

  def show
    @user = User.find(params[:id])
    @photo = @user.photos
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class='container' style="text-align :justify; ">
      <p><%= alert %></p>
      <p><%= notice %></p>
      <%= yield %>
    </section>
  </body>
</html>

app/views/pages/index.html.erb
<h1 style="color: green;">
  Greetings! I'm Instagram_Clone</h1>
<p>Join us to share photos of you with your friends.</p>

<% if current_user %>
  <p>Logged in as <%= link_to current_user.email, user_path(current_user) %></p>
  <%= link_to "My Photos", photos_path %>
<br><br>
  <%= link_to 'Logout', logout_path %>

<% else %>
  <p>Already a member? <%= link_to 'Login', login_path %></p>
  <p>Not yet registered? <%= link_to 'Sign up', signup_path %></p>
<% end %>

app/views/photos/index.html.erb
<% if @photos.try:any? %>
<ul>
  <%= @photos.each do |photo| %>
    <li><%= link_to photo.caption, photo_path(photo) %></li>
  <% end %>
</ul>
<% else %>
  <p>No records found.</p>
<% end %>
<br>
<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= form_for @photo, action: "save" do |form| %>
  <%= form.label :file %>
  <%= form.file_field :file %>
<br>
  <%= form.label :caption %>
  <%= form.text_field :caption %>
<br>
  <%= form.submit %>
<% end %>

app/views/photos/show.html.erb
<% if @photo.file.attached? %>
  <%= image_tag @photo.file %>
<% else %>
  <%= image_tag 'placeholder.png'%>
<% end %>
<br>
<%= @photo.caption %>
<%= link_to @photo, method: :delete, data: { confirm: 'Are you sure?'} do %>
<i class="fas fa-trash-alt"></i>
<% end %>
<br>
<p>Posted by: <%= @photo.user.email %></p>



  <%= form_for ([@photo, @comment]) do |form| %>
    <%= form.text_area :body, placeholder: 'Add comment here' %><br>
    <%= form.submit %><br>
    <% end %>

<% if @photo.comments.any? %>
  <ul>
    <% @photo.comments.each do |comment| %>
      <li style='color:green;'><%= comment.body %></li>
      <%= link_to @photo_comment_path, method: :delete, data: { confirm: 'Are you sure?'} do %>
      <i class="fas fa-trash-alt"></i>
      <% end %>
      <% end %>
    </ul>

    <% else %>
      <p>No comment yet.</p>
    <% end %>
    <br>
<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <%= form.label :email %>
  <%= form.text_field :email %>
<br>
  <%= form.label :password %>
  <%= form.password_field :password %>
<br>
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
<br>
  <%= form.submit %>
<% end %>

app/views/users/show.html.erb
Signed in as <%= @user.email %>

<section class="row">
  <section class="col-md-4">
      <% @photo.each do |photo|%><br>
        <% if photo.file.attached? %>
          <%= image_tag photo.file %>
        <% else %>
          <%= image_tag 'placeholder.png' %>
        <% end %>
        <br>
        <%= photo.caption %>
        <%= link_to photo_path(photo), method: :delete, data: { confirm: 'Are you sure?'} do %>
        <i class="fas fa-trash-alt"></i><br>

        <% end %>
      <% end %>
  </section>
</section>